### ISSUE TITLE
How can i show pagination from a custom query in Screen. thanks

### ISSUE THREAD

**Issue by nguyenkhoi2806** [orchidsoftware/platform#1006]

**Comment by Nks** [comment]
@nguyenkhoi2806 please provide example how you are trying to do that.

**Comment by nguyenkhoi2806** [comment]
> @nguyenkhoi2806 please provide example how you are trying to do that.

this is my code, i would like to add add  a pagination in from this function query, is it possible ?
![Screenshot from 2019-11-05 11-40-17](https://user-images.githubusercontent.com/16773113/68179183-764c6580-ffc1-11e9-9790-47cd4c6a4c65.png)

**Comment by Nks** [comment]
@nguyenkhoi2806 This is not related to the orchid platform. Please check how you can paginate array with laravel. eg. https://arjunphp.com/laravel-5-pagination-array/

**Comment by tabuna** [comment]
@nguyenkhoi2806 

Could you show what the getAllProjects () method does, I think it can be made more simple. Since this code, even with pagination, you will download all records from the database.

As for the question itself, you need to create the object explicitly, for example:
```php
// ...

$collection = collect($collection);

$page = 1;
$perPage = 10;

$paginate = new LengthAwarePaginator($collection->forPage($page, $perPage), $collection->count(), $perPage, $page, ['path'=>url('api/products')]);
```


But I’m sure that you really don’t want it and you don’t need it. For this, I will give a small example of how I would do this:

**Model**
```php
//...

/**
 * Scope a query to only include active project.
 */
public function scopeActive(Builder $query): Builder
{
    return $query->where('active', 1);
}
```

**Screen**

```php
public function query(): array
{
    return [
        'projects' => Project::active()->paginate()
    ];
}
```

**Table**

id,title,owner,acreate,province,distric

```php
//...

TD::set('id'),
TD::set('title'),
TD::set('owner'),
TD::set('acreate')    
    ->render(function ($project) {
        return (float) $project->acreate;
    }),

//... etc
```


Let me know if you need help.
