### ISSUE TITLE
Background reload notifications

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#1009]
Currently notifications system is really good, but problem that the notifications wont reload in the background while user not reloading the page.

Suggestion is easy: make one request every 10 seconds to the notifications controller and badge if we received any notification. 

Other solution: subscribe user on websocket.

What do you think?

**Comment by tabuna** [comment]
By user notifications you mean ` \Orchid\Platform\Notifications\DashboardNotification` ?
I like the web socket, we could use it optionally.

**Comment by Nks** [comment]
Exactly.

**Comment by osbre** [comment]
You also may think about customizable broadcast driver.
Laravel [already](https://github.com/beyondcode/laravel-websockets-demo/blob/master/config/broadcasting.php#L18) have it, only remains ability to change frontend - **laravel-echo** instance (because some drivers have another port, broadcaster, etc)

**Comment by tabuna** [comment]
Currently, I see three different replenishment options:

**Broadcast**
To do this through [Broadcast](https://laravel.com/docs/6.x/broadcasting), where the user chooses the driver himself own ratchet, webpush, nodejs and etc. But this will require additional installations and can greatly increase the threshold for entering the application. It may also be too redundant to use such a solution for one such task.

**Interval**
We could also add a new handler that received and updated this item. I don’t think that it will create any kind of load on the web server or database, hoping that users create an intranet for a limited number of users.

**Worker**
Using a web worker is very similar to the interval, but will only have one update regardless of the number of tabs, which will reduce the number of requests. But it will require a mandatory https connection.


`Web sockets` and `Workers` has the prospect of being reused in the project in other places, for example, we could implement [browser notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) directly, but the interval is very simple and attractive.

**Comment by tabuna** [comment]
I think it would be strange to update only personal notifications, since menu items can also have badges:

![image](https://user-images.githubusercontent.com/5102591/68286742-a879c800-0092-11ea-8322-4844c874f999.png)

Most likely, it will be necessary to render the menu completely, asking for the HTML part (Yes, js fans will forgive me).


And in order to highlight personal ones, add a badge to the favicon, this will be clearly visible to a user who is not in the current tab. For a more contrasting designation, you can change the color to dark:

![Снимок экрана от 2019-11-06 12-37-33](https://user-images.githubusercontent.com/5102591/68286542-5042c600-0092-11ea-9f90-577f746bdbc9.png)


What do you think of it?

**Comment by Nks** [comment]
As I know broadcast needed additional service which is not using by everybody (pusher or redis). Correct me if I am wrong.

**Comment by tabuna** [comment]
The last few days I spent trying to implement some of the calls.

Unfortunately, building a menu is not an option, as we begin to lose the state of existing elements:
- Active element
- Open menu

Also, to work in a hotel template, it would be necessary to break backward compatibility in the definition of `view::compose`

We can still release a separate update for personal notifications, but not a badge menu.

**Comment by tabuna** [comment]
![screencast-orchid software-2019 11 19-01_26_24](https://user-images.githubusercontent.com/5102591/69100634-a8080680-0a6e-11ea-815d-98b38d8366a6.gif)

**Comment by tabuna** [comment]
Unfortunately, I could not achieve a high level with the management of the favicon at the moment.

The problem is the delay in rendering and not always predictable caching with expectation. Currently, this is more costly than adding value.


If you are interested, here is the [last commit](https://github.com/orchidsoftware/platform/commit/2a60e67b5d2fd88672b0047e58c7cd19efcdcccf) that adds this functionality. It will not be in the release without someone's support.

```javascript
import {Controller} from 'stimulus';

export default class extends Controller {

    /**
     *
     */
    initialize() {
        this.data.set('originalFavicon', this.favicon);
    }

    /**
     *
     * @param isUnreadNotice
     */
    notice(isUnreadNotice = true) {
        const img = document.createElement('img');
        img.src = this.data.get('originalFavicon');

        const lineWidth = 2;
        const canvas = document.createElement('canvas');

        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;

            const context = canvas.getContext('2d');

            context.clearRect(0, 0, img.width, img.height);
            context.drawImage(img, 0, 0);

            if (isUnreadNotice) {
                const centerX = img.width - (img.width / 5) - lineWidth;
                const centerY = img.height - (img.height / 5) - lineWidth;
                const radius = img.width / 5;

                context.fillStyle = '#dc3545';
                context.strokeStyle = '#ffffff';
                context.lineWidth = lineWidth;
                context.beginPath();
                context.arc(centerX, centerY, radius, 0, Math.PI * 2, false);
                context.closePath();
                context.fill();
                context.stroke();
            }

            // Replace favicon
            this.favicon = canvas.toDataURL('image/png');
        };
    }

    /**
     *
     * @returns {*}
     */
    get favicon() {
        return this.element.href;
    }

    /**
     *
     * @param href
     */
    set favicon(href) {
        this.element.href = href;
    }
}
```

Perhaps this will appear but not at the moment.

As for the update in the background. That it works well and will be available soon

**Comment by tabuna** [comment]
Now it's in released
