### ISSUE TITLE
Image preview not shown after selecting image in Picture or Cropper field

### ISSUE THREAD

**Issue by ryanchanplc** [orchidsoftware/platform#1071]
Hi,  I found an issue for the Picture or Cropper field. 
The image preview above " Browse" button  is not showing after selecting image using the "Browse" button.
The src attribute in the image tag is pointing to a file in storage folder (that is not exist before update).
After clicking "Update" on the screen, the preview is correctly show. 

  1. Create a Cropper or Picture field
  2. try "Browse" and select a image.
  3. The selected image is correctly shown in the cropper box if it is a Cropper field. click "Crop"
  4. Selected/Cropped Image is not shown in the Cropper or Picture field
  5.  In Developer Tools > Console : 
`Failed to load resource: net::ERR_CONNECTION_REFUSED. `
The src attribute in the image tag is a file from /storage/ folder rather than a base64 string
  6.  Click "Update" the screen and go back to the record, the image is now showing correctly.

Please help! Thanks!

**Comment by tabuna** [comment]
Hey  @ryanchanplc . 

Most likely the problem is that different addresses are specified.
Verify that the address in env matches what you specify in the browser.

For example, if localhost is specified in .env
```bash
APP_URL=http://localhost
```
And you run with the help of the artisan command (http://localhost:8000).
Since the addresses are different, this error occurs. 
```bash
APP_URL=http://localhost:8000
```
You just need to change this value, clear the configuration cache, and restart the server start command

**Comment by ryanchanplc** [comment]
Hi ,

It is resolved by your suggestion, Thanks a lot !
