### ISSUE TITLE
Any docs about localizing the dashboard?

### ISSUE THREAD

**Issue by alash3al** [orchidsoftware/platform#1114]
If I want to translate the dashboard to another language (a business need), how should it go? is it a simple `lang/en/file` ?

**Comment by tabuna** [comment]
Hi @alash3al . I moved this question to a more suitable repository.

All localization relies on the capabilities of the framework. As an example:

Change the language setting in the file `config/app.php`
```php
/*
|--------------------------------------------------------------------------
| Application Locale Configuration
|--------------------------------------------------------------------------
|
| The application locale determines the default locale that will be used
| by the translation service provider. You are free to set this value
| to any of the locales which will be supported by the application.
|
*/

'locale' => 'jp',
```

After we create the file `jp.json` in the directory `resources/lang/` so that the full path would be
`resources/lang/jp.json`. This file will contain plain text in JSON format, for example, add the lines there:

```json
{
    "Systems": "システム"
}
```

After that, we can see the result of our work in the browser:

![image](https://user-images.githubusercontent.com/5102591/83338293-b790c380-a2cb-11ea-8bed-6330b446928b.png)

**Comment by tabuna** [comment]
I will close this question. If the answer didn’t help you, please open it again.
