### ISSUE TITLE
Posibility to override the view of a field

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/platform#1511]
**Is your feature request related to a problem? Please describe.**
in most cases the view of field works perfectly, but in some cases it would be needed to customize the view that is used to render a field.

e.g. Be able to add a title to a Groupe

**Describe the solution you'd like**
An option to specify the view to be used on a field
e.g. Groupe::make([....])->view('my_custom_view');

**Comment by tabuna** [comment]
You can give a more detailed example. Where will this template be inserted?

**Comment by rabol** [comment]
e.g /Screen/Fields/CheckBox.php
most of the fields have a 

`protected $view = 'platform::fields.checkbox';`

but as that is a protected value it is not 'possible' to override it

**Comment by tabuna** [comment]
This is to protect classes from rash changes. But at the same time, be able to inherit and create your own field.

```php
class MyField extend Checkbox
{
    protected $view = 'custom-template';
}
```
You can also do this dynamically for your own fields.

**Comment by rabol** [comment]
I understand that I can create my own fields, but a more fluent way would be a view() method just as in other parts like the ::rows

**Comment by tabuna** [comment]
I'll try to explain with an example.

Suppose I wrote, calling such a field.

```php
CheckBox::make('withTrashed')
    ->sendTrueOrFalse()
    ->placeholder('Show deleted entries')
```

Then I decide to change to a different template (How do you suggest): 

```php
CheckBox::make('withTrashed')
    ->sendTrueOrFalse()
    ->placeholder('Show deleted entries')
    ->view('my_custom_view');
```

How do I know if I need to implement the `sendTrueOrFalse` method?

And with more complex fields that have many methods like `Select\Relation\Matrix`. We will force you to implement all methods and understand how it works inside. For example, what if someone adds a new method and line to the template? This method will not work for the user since its result was not displayed in the template. Therefore, it is best to create your own fields and distribute them, also through GitHub. You can learn how to create your own field and how the builder works on this page https://orchid.software/en/docs/builder/.

**Comment by rabol** [comment]
```
public function setView($view): self
    {
        $this->view = $view;
        return $this;
    }
```

Of course, if someone chose to add a new blade view, then it's his responsibility to ensure that the field is rendered correctly, the same goes for creating a new field that extends a existing field and set the view.
