### ISSUE TITLE
Keep url data on filtering

### ISSUE THREAD

**Issue by urmatt** [orchidsoftware/platform#1862]
I think where good think if after filtering table data 
saves old url params.

At time after doing any filter old url data cleaned.

Thank you!

**Comment by tabuna** [comment]
You can store them in session. Or do you mean something else?

**Comment by zenati** [comment]
@tabuna he means query strings.

**Comment by tabuna** [comment]
Hi, I think you are talking about these filters?


https://user-images.githubusercontent.com/5102591/137042988-ccf329ae-d84d-4fbf-bccd-4676b6a3b23d.mp4


As you can see in the video, I cannot reproduce the data loss of the filters. But I can assume that you forgot to provide a value for the filter fields to save them. For example:

```php
namespace App\Orchid\Filters;

use Illuminate\Database\Eloquent\Builder;
use Orchid\Filters\Filter;
use Orchid\Screen\Field;
use Orchid\Screen\Fields\Input;

class NameFilter extends Filter
{
    /**
     * @var array
     */
    public $parameters = [
        'name'
    ];

    /**
     * @return string
     */
    public function name(): string
    {
        return 'Name';
    }

    /**
     * @param Builder $builder
     *
     * @return Builder
     */
    public function run(Builder $builder): Builder
    {
        return $builder->where('name', $this->request->get('name'));
    }

    /**
     * @return Field[]
     */
    public function display(): array
    {
        return [
            Input::make('name')
                ->value($this->request->get('name'))
        ];
    }
}
```

Since the filter can be complex, we do not automatically substitute the value in the field:

```php
Input::make('name')->value($this->request->get('name'))
```

If that's not what you meant. Or does not solve your problem, please provide steps to reproduce
