### ISSUE TITLE
Nested Matrixes

### ISSUE THREAD

**Issue by TheFehr** [orchidsoftware/platform#1890]
**Describe the bug**
When nesting a matrix inside a matrix quite a few things break:
- The remove row button of the inner matrix removes the complete outer row.
- The add row button of the outer matrix does nothing after the first row. (JS error in console seems to indicates it trying to add a row in the inner matrix)

**To Reproduce**

  1. Add a crud resource
  2. Add a matrix with a matrix as a child in the fields array

**Expected behavior**
- The inner remove button removes the inner rows
- The outer add buttons can add more than one row

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 93.0.4577.82 

**Server (please complete the following information):**
  - Platfrom Version: 10.16.0
  - Laravel Version: 8.61.0
  - PHP Version:  8.0.10
  - Database:  MySQL / MariaDB

**Comment by tabuna** [comment]
I think that it is worth considering the possibility of splitting your JSON into several Matrix fields so that it would be convenient to edit and then collect into the desired structure. I don't think nesting a matrix into another matrix is a good solution. There are no plans to support this capability.
