### ISSUE TITLE
Multiple Select with Empty Data

### ISSUE THREAD

**Issue by DarkNightHome** [orchidsoftware/platform#1948]
**Bug Multiple Select**
In Modal Window When open multiple select open incorrectly

**To Reproduce**

  1. Create Modal Form
  2. Add Select Multiple Element with Options by array values
  3. Open and see not correcten view and no dropdown menu

**Expected behavior**
When put data with array (when edit) then look normal and select open dropdown menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/6933642/139197548-78b26f54-ebdc-42ba-a624-ae6dd7fc7e61.png)
![image](https://user-images.githubusercontent.com/6933642/139197608-d1a3896b-208a-48cd-8dc5-617c3b3a7544.png)

**Desktop (please complete the following information):**
 - OS: Linux Debian 10
 - Browser Chrome
 - Version 95

**Server (please complete the following information):**
  - Platfrom Version: latest
  - Laravel Version: latest
  - PHP Version:  7.3
  - Database:  mariadb
  - Database Version:  10

**Comment by tabuna** [comment]
Hi, I cannot reproduce this. Created a modal window with the following content:

```php
Select::make('test_modal_select')
    ->multiple()
    ->options(['foo','bar','baz']),
```

I saved the values and selected them again. 
I also tried to close and open. But this did not lead to the same look as in your screenshots.


----

The only thing that led to this behavior was the complete duplication of the field on the pages. 
For example, one on the page, the other in a modal window:

```php
Layout::modal('selectModal', Layout::rows([
    Select::make('test_modal_select')
        ->multiple()
        ->options(['foo','bar','baz'])
        ->required(),
])),

Layout::rows([
    Select::make('test_modal_select')
        ->multiple()
        ->options(['foo','bar','baz']),
])
```


The quick solution is to use a different name prefix for modals. 
At the moment, I'm not sure where this issue is happening in the [dependent library](https://github.com/select2/select2) or in our [controller](https://github.com/orchidsoftware/platform/blob/c2dfc682c84b6c7dfa70c5a5b177be31b82f4ec7/resources/js/controllers/select_controller.js#L1).
