### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by mouadh-dev** [orchidsoftware/platform#2255]
**Describe the bug**
i am trying to upload pictures with crud and what I get is "sha1_file(): Argument https://github.com/orchidsoftware/platform/issues/1 ($filename) must be of type string" error (from developer inspection tool).

**To Reproduce**

  1. Laravel 9, PHP 8.1, Orchid 12.5.0
  2. Create simple crud with Picture or Cropper or Upload
  3. try to upload a file

**Expected behavior**
I expect to upload the picture or the file normally.

**Screenshots**

![Screenshot 2022-05-31 104809](https://user-images.githubusercontent.com/62395675/171145823-a26801d7-f506-43b4-90db-1a212cfcf0c5.jpg)

**Desktop (please complete the following information):**
 - windows 11
 - opera gx

**Additional context**
I think the same bug is in screen

**Comment by khalifa-dv** [comment]
hello @mouadh-dev @HijenHEK   @tabuna ,
the issue is  about version php 8.0.12 and  >8.0.12,
u must upgrade your version PHP 8.0.13,
you can see patch in PHP 8.0.13
-MBString:
Fixed bug [#76167](http://bugs.php.net/76167) (mbstring may use pointer from some previous request). 
Description:
------------
mbstring seems to assume that calls to rinit are matched with calls to rshutdown, but this may not be case. In particular, if another extension fails its rinit (after mbstring has run its), either by returning FAILURE or calling zend_error(), then rshutdown will never be called, as PG(modules_activated) will be 0.

**Comment by astersnake** [comment]
An issue exist with this same description in https://github.com/orchidsoftware/platform/issues/2252
