### ISSUE TITLE
Using orchid native icons with dynamic template

### ISSUE THREAD

**Issue by dragonares5** [orchidsoftware/platform#2401]
**Is your feature request related to a problem? Please describe.**
Currently looks like there is no way to use Orchid Icons dynamically in JS when you are creating a template.

**Describe the solution you'd like**
As in FontAwesome, it would be usable by class names.

I don't know if there was consideration for dynamic template when the issue #1061 was made.

```JS
_createTableItemTemplate(){
    return `<tr>
      <td>3929840</td>
      <td>MATER. INCLUSIOVO E DISPERSIVO</td>
      <td>
        <input class="form-control" type="number" name="pecas[][quantidade]">
      </td>
      <td>
        <button class="btn btn-danger py-2 mt-1 d-flex justify-content-center" data-action="click->pv-pedido-cliente#onRemoveItem">
          <x-orchid-icon path="minus" class="icon-minus" />
        </button>
      </td>
    </tr>`;
  }
```

The only alternative I found was doing a require directly from composer vendor directory as `<img src="${require("../../../vendor/orchid/icons/svg/minus.svg")}">`

**Comment by tabuna** [comment]
We rely entirely on server-side rendering, so we don't specially prepare icons for JS control. However, this does not mean it is not possible, you can use the existing <template> tag `<template>`:


For example, place code in page:
```html
<template id="product-row">
  <tr>
      <td>{name}</td>
      <td>
          <x-orchid-icon path="minus" class="icon-minus" />
      </td>
  </tr>
</template>
```

and JavaScript code:

```js
let template = document.querySelector('#product-row');

let row = template.content.querySelector('tr').cloneNode(true);
row.innerHTML = row.innerHTML
    .replace(/{name}/gi, "Alexandr");
```

This allows you to create a DOM element with the content you want from a template (e.g., instead of a placeholder name, the actual content). All you have to do is insert it where you want it.

This is how the Matrix field works, for example
