### ISSUE TITLE
Annoying message box when data in page changed 

### ISSUE THREAD

**Issue by aminemeickel** [orchidsoftware/platform#2715]
**Describe the bug**
I am not sure that this is a bug but i am looking to stop this behavior on some page or remove it completely i am using orchid 14.12.0  

**To Reproduce**

  1.Create a page
  1.add Input filed in page
  1.change the data in that field and then try to change the page

**Expected behavior**
Remove this behavior completely 

**Screenshots**
![image](https://github.com/orchidsoftware/platform/assets/68289833/7847aa10-d0a8-406d-95ee-38c7f0acb9d7)

**Desktop (please complete the following information):**
 - OS: 11
 - Browser : chrome, mozilla
 - Version latest to this day 

**Server (please complete the following information):**
  - Platfrom Version: 14.12.0
  - Laravel Version: 10.x
  - PHP Version:  8.1
I didn't find anything in documentation please help
thanks

**Comment by tabuna** [comment]
Hi @aminemeickel! This intentional behavior is called "Prevents Abandonment."

There are two ways to manage this feature:

- Firstly, you can disable it by modifying the configuration file for all screens by default.
 Simply follow the link to see the file:

https://github.com/orchidsoftware/platform/blob/cba008b0bfaa05f6e6dbd3ee3c313f854b96011c/config/platform.php#L295-L306

- Secondly, you can override this function only for a specific screen. 
Here's the link to the file where you can do that:

https://github.com/orchidsoftware/platform/blob/cba008b0bfaa05f6e6dbd3ee3c313f854b96011c/src/Screen/Screen.php#L369-L377

I hope this helps! If you have any more questions, feel free to ask.

**Comment by aminemeickel** [comment]
Thank you so much for the respond it's super helpful you are the best
