### ISSUE TITLE
Conditional fields for filters

### ISSUE THREAD

**Issue by korundKrona** [orchidsoftware/platform#2868]
Is there any solution to be able to control the visibility of filters through the value of another field?

**Comment by tabuna** [comment]
In Orchid, filters, like any other classes, can be created and configured explicitly. Instead of using a static filter call, like in the following example:

```php
Model::filters([EmailFilter::class])->simplePaginate();
```

you can write code that creates an instance of the filter with additional parameters. For example:

```php
$conditional = false;

Model::filters([
    new EmailFilter($conditional)
])->simplePaginate();
```

In this case, you will need to handle the provided value (`$conditional`) in the constructor of your filter. This approach allows you to configure the filter’s behavior according to your specific requirements.
