### ISSUE TITLE
Form fields vertical per default 

### ISSUE THREAD

**Issue by anxgstadler** [orchidsoftware/platform#2899]
**Describe the bug**
The documentation clearly states: "By default, form elements are displayed in a horizontal layout, with the label and input field side by side."
See: https://orchid.software/en/docs/field/#designing-input-interfaces

However, I need to add horizontal() to each and every field to get the label next to the input field. The default rendering seems to be vertical instead of horiziontal.

Now, this ticket might be either ...
1) a documentation issue. If so, please update the docs.
2) or a bug. If so, please make the fields behave correctly.
3) or result in a feature request: It would be nice if I could set some configuration somewhere that by default all inputs should render either horizontally or vertically without me having to call the methods on every input.

**To Reproduce**

1) Create a vanilla installation of Orchid
2) The demo forms like e.g. editing a role or a user will already display as vertical form fields.

**Expected behavior**
Labels being displayed left of input fields

**Server (please complete the following information):**
  - Platfrom Version: 14.34.0
  - Laravel Version: v11.22.0

Thanks!

**Comment by macit-emre** [comment]
this is a free open source project. We are currently using this, and we like the way @tabuna can do his best.
in 10 minutes, the classes all can be extended and ready to use.  Or teach your GPT to do this for you. Or use find & replace.

In every project, frontend is an issue. So , make it your way.

Filament is more shiny, but orchid is much faster to develop. 

That's all my opinion.

**Comment by macit-emre** [comment]
That is the absolute risk of open source. This conversation is likely being converted to another subject. 
So you may use at your own risk. If you buy consultancy from tabuna, (i dont know that if he is doing such a job) you may relax a bit. And then? if he dies? :)

Come to us ! We get a little bit orchid expert in 2 years. :P Have a good day.

**Comment by tabuna** [comment]
It seems like Orchid might not have left the best impression on you, and that’s totally okay! It’s natural to prefer solutions that better suit your needs.  

Just to share a bit of context, I’ve been working on this project mostly solo since 2016, so it’s a labor of love for me. But you’re absolutely right—community is not something Orchid can boast about, and that’s a completely fair observation.  

That said, I truly believe in the potential of every contributor and try my best to create a welcoming and supportive space for anyone who wants to get involved. 

Regarding your issue, here’s a simple example of how you can create a custom class to display your fields horizontally:

```php
namespace App\Orchid\Layouts;

use Orchid\Screen\Field;
use Orchid\Screen\Layouts\Rows;

class HorizontalRows extends Rows
{
    public function __construct(protected array $fields = []) {}

    protected function fields(): iterable
    {
        return collect($this->fields)
            ->map(fn(Field $field) => $field->horizontal());
    }
}
```

You can then use it in your screens:

```php
protected function layouts(): iterable
{
    return [
        new HorizontalRows([
            Input::make('...'),
            Input::make('...'),
        ]),
    ];
}
```
