### ISSUE TITLE
Menu page bindings

### ISSUE THREAD

**Issue by angay9** [orchidsoftware/platform#435]
Hello. I have a question/improvement proposal. 
Right now there is no way to bind a specific page to a menu item (at least I didn't find a way to do it).
Is it possible to add this feature? Or this goes against the Orchid philosophy.

Another question is what is the best approach to add/edit text pages which would have the same layout but would only have different content? Should I create a new ManyBehavior named Page for instance and go from there?

Thank you for all the job you're doing, I really like Orchid and would like to understand it better and help to improve it.

Thank you

**Comment by PSalador** [comment]
On question 2 answer.
Yes, you can create a new ManyBehavior, or edit an existing DemoPost.

**Comment by tabuna** [comment]
Hey. Adding existing routes is not yet possible, because there are dozens of system routes (not only in this package), their system name will not give information to the user. If you have suggestions, I will gladly consider this.

If you change only one content, create multiple behaviors, so you can add new functionality at any time, change or completely get rid of them, without harming other data.

(Google Translate)

-----
Привет. Добавлять уже существующие маршруты пока не представляется возможным, потому, что существует десятки системных маршрутов (не только в этом пакете) их системное название не даст информации для пользователя. Если у вас есть предложения я с радостью рассмотрю это.


Если у вас меняется только один контент, создавайте множественные поведения, таким образом, вы сможете в любой момент добавить новый функционал, изменить или вовсе избавится от них, без вреда для других данных.

**Comment by angay9** [comment]
Hi. Thank you for your response. Even though I understand everything perfectly in Russian, I'm going to write in English so everyone who sees this will get an idea of what is going on. 
I believe that Orchid can be used very often for managing websites, because It allows to easily and quickly create and manage content. 
I also think that because there is no way to attach behavior to a menu item it limits orchid's potential a bit.

My proposition is more abstract right now, because I don't have a concrete implementation at this moment (I might come up with a PR in the future).
Here is an example of what Menu might look like:
Add a new field to menu table in database called **link** - the information about target module or target behavior will be stored. So for instance, if I want a menu item to be connected with a single blog post - then this field would have a value of "@post/2", where the first part after "@" is the slug of behavior, and the second part after "/" is an id of a behavior record.

Each behavior might also have a method called **forMenu()**, which could return a collection of items that can be added to a menu item. If it returns false, then this behavior might not be added a menu.

Another idea is to implement menu like PageKit CMS has, where you can link to all the pages in your system, as well as blog posts or even files from the storage.

These ideas are very raw, yet I hope that they can help you/us create a more dynamic menus.

**Comment by aios** [comment]
@tabuna а я вот его понимаю) И я тебе больше скажу - он не единственный такой.
