### ISSUE TITLE
Error: The Mix manifest does not exist

### ISSUE THREAD

**Issue by amirakbulut** [orchidsoftware/platform#663]
I installed the master branch through composer and followed the Installation guide, however when I'm visiting /dashboard in my browser, I'm getting an exception error saying the Mix manifest does not exist.

### Expected Behavior
Visit /dashboard -> Show dashboard view.

### Actual Behavior
Visit /dashboard -> Exception error.

The Mix manifest does not exist. (View: C:\xampp\htdocs\X\vendor\orchid\platform\resources\views\layouts\auth.blade.php) (View: C:\xampp\htdocs\X\vendor\orchid\platform\resources\views\layouts\auth.blade.php)

### Specifications

  - ORCHID Version: Latest Master branch
  - Laravel Version:  5.6.24
  - PHP Version: 7.2.5
  - Database Version: mysql  Ver 14.14 Distrib 5.7.21, for Win32 (AMD64)

How do I solve this?

**Comment by tabuna** [comment]
Thank you for taking the time to report the problem.

The [package creates symbolic links](https://orchid.software/en/docs/installation#publish-preferences) for accessing js and css, as well as for storing files,
using two built-in commands:

```bash
php artisan storage:link
php artisan orchid:link
```

Some environments do not allow this to happen automatically (due to lack of command or due to lack of rights or any other reason). Maybe by using `xampp`, we have this problem.

Are links to directories created in `C:\xampp\htdocs\X\public\orchid` ?


If not, and the command does not help you, open the `cmd`, go to the project directory and make them [manually](https://orchid.software/en/docs/installation#publish-preferences):

> Notice. Come platforms (vagrant) can not create symbolic links with this commands. And it may become necessary to manually perform the following commands cp -rf vendor/orchid/platform/public public/orchid and mkdir -p public/storage/public


_This should work for you. Remember to add them to gitignore_
