### ISSUE TITLE
forms pages in website gives 404

### ISSUE THREAD

**Issue by hmzlam** [orchidsoftware/platform#738]
the forms pages in website gives 404
[https://orchid.software/en/docs/form](https://orchid.software/en/docs/form)

**Comment by tabuna** [comment]
Forms have been removed since version 3, thanks for noticing this misstep.
They will remain forever in our history and will be [available in the repository by tag](https://github.com/orchidsoftware/platform/blob/a61e0f36d45555eb8388b886c5090f391a9a61df/docs/en/form.md).

At the moment we offer a more convenient version of the description of forms consisting of **fields** (Text field, etc.), **layouts** (Tabs, lines, modal windows, etc.) and **screens** (Class that describes their relatedness)

When installing the package, an example of the class and its use will be ready and you can try them out without any additional actions.
