### ISSUE TITLE
[Draft] Conditional fields

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#774]
This will be really helpful add an ability to set the conditional fields which can appear only when it really needed. I know that this is possible with the rules, but in the screens page still overloaded with a lot of not needed all time fields.

Open to discuss

**Comment by tabuna** [comment]
It seems to me reasonable to assign conditions, but not for the fields, but for the layers. 
What was already in #733 . 

```php
namespace Orchid\Screen\Layouts;

use Orchid\Screen\Repository;

/**
 * Class Base
 */
abstract class Base
{
    /**
     * @param $query
     *
     * @return bool
     */
    public function canSee(): bool
    {
        return true;
    }
}
```

You can add rows, tables, tabs, etc. depending on user rights, this also works for buttons.

The indication for each field is a bit redundant.

**Comment by Nks** [comment]
```
DependenceField::make()
    ->set(CheckBoxField::какое то определение)
    ->with(true,'набор полей при true')
    ->with(false,'набор полей при false')
```

**Comment by Nks** [comment]
Also Layers doesn't support by entities as I know and this can be a potential problem. Also this should happens on fly instead of work with the php side

**Comment by tabuna** [comment]
```php
CheckBoxField::make('is_show_banner'),

InputField::make('conditional_field')
    ->at('is_show_banner', '==', true)
```

**Comment by tabuna** [comment]
I want to come back to this issue and implement it. 
The main suggestion will be to use a separate layer for this.

Let's say that our screen contains the following layer with a field:
```php
Layout::rows([
    CheckBoxField::make('is_show_banner'),
]),
```

The simplest option in my opinion would be something like:

```php
Layout::condition('is_show_banner')
    ->when(true, MyCondiditonRow::class);
    ->when(false, OtherCondiditonRow::class);
```
It looks short and seems to be nice.
But the values for our dependent fields will be taken from the `query()` method. This may prevent us from costing more complex fields, for example, when choosing a country, asking to choose a city, etc. Since we need to know the custom value and access the database to form the values for the fields.


In theory, we can use an asynchronous call.

```php
Layout::condition('is_show_banner')
    ->when(true, MyCondiditonRow::class);
    ->when(false, OtherCondiditonRow::class);
    ->async('asyncStrategy')

//...

public function asyncStrategy($value = null)
{
    $banner = 'default';

    if ($value) {
        // more your code
        $banner = '5x6-8061*56';
    }

    return [
        'banner_code' => $banner,
    ];
}
```

If you combine these two approaches, then we can both get the values and return the ones we need.

Also, the borderline case may be the other way round, inclusion for all but some of the values. To do this, we will need to use the callable type:

```php
Layout::condition('is_show_banner')
    ->when(function ($value) {
        return $value !== 'ignore';
    }, MyCondiditonRow::class);
```

This is only a draft. If you have suggestions for improvement, please feel free to
