### ISSUE TITLE
Update Tinymce configuration

### ISSUE THREAD

**Issue by brahimbim** [orchidsoftware/platform#889]
### Expected Behavior
 Hello, How to update TinyMCE config file in my application 
![image](https://user-images.githubusercontent.com/24649160/59386399-7c198400-8d5e-11e9-88c7-df4bb0e0ad5a.png)

### Specifications

  - ORCHID Version:5.0.3
  - Laravel Version:5.8
  - PHP Version:7.3
  - Database Version: Mysql 5.7

**Comment by tabuna** [comment]
@brahimbim 

At the moment, you can only change the design theme, but not the tools on the panel.

```php
TinyMCE::make('html')->theme('inlite');
//or
TinyMCE::make('html')->theme('modern');
```

You can also inherit from the form class and write the desired behavior. But this requires writing your own javascript script.

-------

I have thoughts on this, but I'm not sure on average.

We could add options as allowed properties so that they are described in php as other parameters
```php
TinyMCE::make('html')
    ->option1()
    ->option2()
```

Another option is to add javascript callback:
```javascript
function tinymce_init_callback(editor)
{
    //...
}
```

The first option can be duplicated many times. And the second is global on all your application.

How would you like to refer to this?
