### ISSUE TITLE
What's going to happen to old Plugins

### ISSUE THREAD

**Issue by mojtabaahn** [orchidsoftware/platform#924]
Hi, As a mater of fact I know that previous versions of Orchid has some good useful plugins ( Actually they were plugged into Orchid's core ) like **file-manager**, **content management stuff** and other good things; and they got removed in latest patches.

I like the idea of separating core library and other stuff but in my experience they were great ( tbh I am using the old file-manager ), so I'm just curious if they are going to reappear in future updates or as complete different packages or any other plans.

**Comment by tabuna** [comment]
Hi @mojtabaahn .

I have been doing this projects since November 16, 2015 and
Indeed, we had a lot of different packages and add-ons.

Most of them either did not become popular, or did not receive the deserved attention on my part.

Here are some of the features that were before:

- [Log Viewer](https://github.com/legacy-orchid/Log)
![image](https://user-images.githubusercontent.com/5102591/62240825-7c3e1380-b3e0-11e9-98c1-565d327db43e.png)

- Database manager
![image](https://user-images.githubusercontent.com/5102591/62240862-9d9eff80-b3e0-11e9-9690-a4626e59c010.png)

-  [System monitor](https://github.com/orchidcommunity/monitor)
![image](https://user-images.githubusercontent.com/5102591/62240895-b4455680-b3e0-11e9-88da-072f4da556b7.png)

- Route builder
![image](https://user-images.githubusercontent.com/5102591/62240957-d3dc7f00-b3e0-11e9-950f-60a29cc70d1d.png)


- File manager
![image](https://user-images.githubusercontent.com/5102591/62241013-f2427a80-b3e0-11e9-9032-ee28cc6c270c.png)

- [Backup](https://github.com/orchidcommunity/backup)
- [Builder](https://github.com/orchidcommunity/builder) (Like)
- [Defender](https://github.com/orchidcommunity/Defender)
- Google Analytics
- Remote (api)
- Widgets
- And many many different variations.


I am afraid that all of them are a thing of the past, I cannot provide everyone with a good level, receive feedback and do basic work every day.

If you spread strength on 10 different packages without a stable and convenient platform, this will be a bad result. That's why I decided not to do such things until the package becomes popular. (I described these solutions and my pain in a blog in Russian)

If you look at Google, then the search results for "Laravel admin / dashboard / platform" you will not find this package there, then what is the chance that people will be interested in packages for it?

The result of such reflections was the rule that I would do what I could maintain for a long time.

All listed packages and add-ons are not included. At the same time, I have a wonderful attitude to people who are developing any additions to Orchid from "XSettings" to "[Repeat](https://github.com/Nks/orchid-repeater-field)" and is ready to provide developers with support or advice.

I do not know if I explained it clearly. But if not, then the short answer to your question will be
 “No, I do not have free time to support all add-ons.”

I can assume that the majority will simply die and new solving problems will appear instead of them even better, but already from users. If they don’t get it, it will be sad but people have many alternatives: sleepingowl, laravel-admin, voyager, backpack, nova.

I have no opportunity to influence what you are asking.

**Comment by tabuna** [comment]
Only users decide what will be popular and what is not. What is a good project and what is not. What to write in a blog and what not. And so on.

This opensource and can be solved only by those who are interested in it. Only through a good active audience can you do this kind of work.
