### ISSUE TITLE
How to contrinute/place to publish packages for ORCHID

### ISSUE THREAD

**Issue by LCD344** [orchidsoftware/platform#975]
**Is your feature request related to a problem? Please describe.**
Me and my team has just found Orchid last week and we love the platform, we will be using this platform for 2-3 new projects soon (and yes, will be contributing as soon as we get paid :) )

But also as we develop will will probably create our own packages for the platform and we were thinking it will be nice to either create pull requests for things that might be added into the core, or that there should be a place to publish our packages for other uses to be able to use them.

**Describe the solution you'd like**
A clear part in documentation describing how to add new packages (like custom fields and layouts) to the main repository, and what kind of submissions will be accepted + coding standards. And maybe a curated github list of known orchid packages?

**Additional context**
~~I already created one package that we think is useful, https://packagist.org/packages/elcoop/orchid-form-row (I'm writing the readme as we speak)~~ I just found out my package wasn't necessary but I think for this amazing platform to keep growing we will need a good way to share those kind of things with each other.

**Comment by tabuna** [comment]
Hey @LCD344 . 

This is a big topic that I think should be divided into several:


**Package**
To create new packages, we made a separate repository ["skeleton"](https://github.com/orchidsoftware/skeleton) which will allow you to deploy a new package in literally minutes. The creation itself is almost no different from creating a simple composer/laravel package. 

**Documentation**
From what we could do in addition is a more detailed description, perhaps a tutorial on how to make your own field or layer. I agree with this and I will be glad if anyone adds such material.


**Coding standards**
I try to make entering the project as softer. Therefore, we use "[StyleCI"](https://styleci.io) so that you do not have to take care of indents and spaces. At the moment, he will make the necessary changes for you.

As regards the documentation of this process directly, unfortunately we do not yet have a translation of some documents into English:
- [Code of Conduct](https://orchid.software/ru/docs/code-of-conduct/)
- [Contributors](https://orchid.software/ru/docs/contributors/)
- [Promote](https://orchid.software/ru/docs/promote/)

In them, we describe how to do PR and talk about how you can influence the project. 
I understand that now this is limiting actions, so I’ll try to make a transfer in the near future.


**Publish packages**
We can create a separate page on the website with a directory of extensions and links to the repository. For example:

- https://novapackages.com/
- https://octobercms.com/plugins

Another option is to create a separate awesome-orchid repository which will describe the most popular packages. For example:

- https://github.com/brillout/awesome-react-components
- https://github.com/its-awesome/awesome-laravel-nova

But I would not want to spend a lot of time on this myself.

**Comment by tabuna** [comment]
Added some documents with machine translation:
- [Code of Conduct](https://orchid.software/en/docs/code-of-conduct/)
- [Contributors](https://orchid.software/en/docs/contributors/)
- [Promote](https://orchid.software/en/docs/promote/)
If possible, go through them

**Comment by Nks** [comment]
@LCD344 you also can check [this package](https://github.com/Nks/orchid-repeater-field/) as example.
