### ISSUE TITLE
url of the uploaded file has additional domain name

### ISSUE THREAD

**Issue by Hrache** [orchidsoftware/platform#993]
Hello. When I'm uploading an image through Cropper it saves everything appropriately but when I'm using the url of the image somehow it adds domain name in front it, and as a result I've something like this:

> http://domain-name/admin/
> +
> domain-name/storage/2019/10/18/f080227ce34db289ed93cef95be5e92a637c25c4.png

(this is the way file was saved in the database)

and this happens when I'm placing the url into the img:src or a:href. this kind of situation I've at this time, how can I fix it, I couldn't find any base tag

**Comment by Hrache** [comment]
I noticed that the actual link is what is in the database, it is the browsers moment, when you hold the mouse cursor on the link it shows the url the way I described above. So what I've done I manually added http:// in front of the url and it actually drew the picture at its place, then I added http:// at .env and platform.php now it saves urls with http:// protocol string as well. Means it works, is possible that the browser is the problem.

**Comment by tabuna** [comment]
Hi, this is due to the work of the laravel builder url for files. In constructing the counted address specified in the configuration (env/config).

You may not save images with a full address. For example:

```php
Cropper::make('post.hero')
    ->targetRelativeUrl(),
```

Then your database will contain:

```php
/storage/2019/08/02/0f92ef693c26f3c1dbe2e3792abac9254ee98310.png
```

I advise you to watch the tutorial: https://orchid.software/en/docs/quickstart-files/
and: https://laravel.com/docs/6.x/filesystem#file-urls

If you think that there is a mistake in the package or we can improve the experience of interaction, please do not hesitate to open it again.
